### ISSUE TITLE
About page links do not work

### ISSUE THREAD

**Issue by domfarolino** [gauntface/gf-site#35]
All of the links under the `SHOUT` section of the about page don't work. I searched some text on the page in the repo and found it's probably because no model values are filling out the `href`s?

https://github.com/gauntface/gf-site/blob/46eba194dc6e33c5e2dbd963705d63ce07fe2a88/src/server/application/views/content/about.php#L33

Didn't look into it too much because....PHP lol

**Comment by gauntface** [comment]
Thanks for this issue, went through a messy change moving to a more app shell model. Will look at writing some tests and fixing this bug.
